export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';
export const USER_LOADED = 'USER_LOADED';
export const USER_NOT_LOADED = 'USER_NOT_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
export const USER_UPDATE_SUCCESS = 'USER_UPDATE_SUCCESS';
export const USER_UPDATE_FAIL = 'USER_UPDATE_FAIL';

export const CLEAR_PETS = 'CLEAR_PETS';

export const PETS_ADD_SUCCESS = 'PETS_ADD_SUCCESS';
export const PETS_ADD_FAIL = 'PETS_ADD_FAIL';
export const PETS_REMOVE_SUCCESS = 'PETS_REMOVE_SUCCESS';
export const PETS_REMOVE_FAIL = 'PETS_REMOVE_FAIL';
export const PETS_UPDATE_SUCCESS = 'PETS_UPDATE_SUCCESS';
export const PETS_UPDATE_FAIL = 'PETS_UPDATE_FAIL';
export const PETS_GET_SUCCESS = 'PETS_GET_SUCCESS';
export const PETS_GET_FAIL = 'PETS_GET_FAIL';
export const PET_GET_SUCCESS = 'PETS_GET_SUCCESS';
export const PET_GET_FAIL = 'PETS_GET_FAIL';